#:kivy 1.10.1
#:import utils kivy.utils

<Button>:
    background_normal: ''
    background_color: utils.get_color_from_hex('#0c90c8')

    canvas.before:
        Color:
            rgba: .0, .0, .0, 1
        Line:
            width: 3
            rectangle: self.x, self.y, self.width, self.height

    font_size: 32
    size: 230, 96

<Agent>:
    size: 120, 96
    canvas:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center
        Rectangle:
            pos: self.pos
            size: self.size
            source : './img/agent.png'
        PopMatrix

<Ball1>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size
<Ball2>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size

<Ball3>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size
<Ball4>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size
<Ball5>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size
<Ball6>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size
<Ball7>:
    color: 0,0,1,1
    size: 12,12
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size

<Game>:
    agent: game_agent
    ball1: game_ball1
    ball2: game_ball2
    ball3: game_ball3
    ball4: game_ball4
    ball5: game_ball5
    ball6: game_ball6
    ball7: game_ball7


    Agent:
        id: game_agent
        center: self.parent.center
    Ball1:
        id: game_ball1
        center: self.parent.center
    Ball2:
        id: game_ball2
        center: self.parent.center
    Ball3:
        id: game_ball3
        center: self.parent.center
    Ball4:
        id: game_ball4
        center: self.parent.center
    Ball5:
        id: game_ball5
        center: self.parent.center
    Ball6:
        id: game_ball6
        center: self.parent.center
    Ball7:
        id: game_ball7
        center: self.parent.center
